In [10]:
import numpy as np

In [16]:
 a = np.array([1,2,3])
a
print(a)

[1 2 3]


In [33]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


THE BASICS

In [41]:
# Get dimension of numpy array
a.ndim

1

In [39]:
b.ndim

2

In [47]:
#Get the shape of a numpy array (rows, cols)
a.shape

(3,)

In [45]:
b.shape

(2, 3)

In [49]:
# Get type
a.dtype

dtype('int32')

In [51]:
b.dtype

dtype('float64')

In [57]:
# Get size (bytes)
a.itemsize

4

In [61]:
# Get total size (elements
a.size * a.itemsize

12

In [63]:
a.nbytes

12

 Accessing / Changing Specific element rows, columns, etc